### ISSUE TITLE
Has a bug in compiling files containing cookiecutter templates.

### ISSUE THREAD

**Issue by thesct22** [karpierz/pyc_wheel#10]
When handling files containing cookiecutter templates the compilation fails. For example,

```
***   File "<my-module-1.2.3>\something\something\_templates\default\{{cookiecutter.__template_name}}\a_file.py", line 3
    from something.abc.{{ cookiecutter.__solution_name_slug }}.xyz.abc import bcdefgh
                       ^
SyntaxError: invalid syntax


Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\pyc_wheel\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\pyc_wheel\_pyc_wheel.py", line 193, in main
    convert_wheel(Path(whl_file), exclude=args.exclude,
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\pyc_wheel\_pyc_wheel.py", line 54, in convert_wheel
    raise RuntimeError("Error compiling Python sources in wheel "
RuntimeError: Error compiling Python sources in wheel mymodule-1.2.3-py3-none-any.whl
```

There should either be an option to ignore cookiecutter templates that are being packaged with a module or a way to handle this edge case.

**Comment by karpierz** [comment]
Sorry, but it is not possible to distinguish the type of file by its content.
Pyc-whell compiles all files with .py extension in the package.
The only way is to change the extension of cookiecutter template files.
